version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: movies

  ecommerapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerapp
    depends_on:
      - postgres
    env_file:
      - .env.docker
    environment:
      - PORT=5555
    ports:
      - '5555:5555'

volumes:
  postgres_data:
